services:
  alpha:
    build:
      dockerfile: Dockerfile
    environment:
      LOG_LEVEL: DEBUG
    networks:
      bridge-net:
        ipv4_address: 10.21.0.42
  
  beta:
    build:
      dockerfile: Dockerfile
    environment:
      LOG_LEVEL: DEBUG
    networks:
      bridge-net:
        ipv4_address: 10.21.0.24

networks:
  bridge-net:
    ipam:
      config:
        - subnet: 10.21.0.0/24
          gateway: 10.21.0.1
