services:
  alpha:
    image: ealen/echo-server:0.9.2
    networks:
      bridge-net:
        ipv4_address: 10.21.0.42
  
  beta:
    image: ealen/echo-server:0.9.2
    networks:
      bridge-net:
        ipv4_address: 10.21.0.24

networks:
  bridge-net:
    ipam:
      config:
        - subnet: 10.21.0.0/24
          gateway: 10.21.0.1
